server {
    listen 80;
    
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Serve sitemap.xml directly
    location = /sitemap.xml {
        root /usr/share/nginx/html;
        default_type application/xml;
        try_files $uri =404;
    }

    # Serve robots.txt directly
    location = /robots.txt {
        root /usr/share/nginx/html;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
